const symbolMap = {
  A: {
    vowel: true,
    example: "At",
    lines: ["tol", "tor", "s"],
    arpa: ["AE"],
  },
  AR: {
    vowel: true,
    example: "ARm",
    lines: ["tol", "tor", "bol", "bor"],
    arpa: [],
  },
  AH: {
    vowel: true,
    example: "swA(H)n",
    lines: ["tol", "s"],
    arpa: ["AA"],
  },
  AY: {
    vowel: true,
    example: "bAY",
    lines: ["tol"],
    arpa: ["EY"],
  },
  E: {
    vowel: true,
    example: "End",
    lines: ["s", "bol", "bor"],
    arpa: ["EH"],
  },
  EE: {
    vowel: true,
    example: "bEE",
    lines: ["tol", "s", "bol", "bor"],
    arpa: ["IY"],
  },
  EER: {
    vowel: true,
    example: "bEER",
    lines: ["tol", "s", "bor"],
    arpa: [],
  },
  EH: {
    vowel: true,
    example: "thE(H)",
    lines: ["tol", "tor"],
    arpa: ["AH", "AX", "AXR", "IX"],
  },
  ERE: {
    vowel: true,
    example: "thERE",
    lines: ["s", "bor"],
    arpa: [],
  },
  I: {
    vowel: true,
    example: "bIt",
    lines: ["bol", "bor"],
    arpa: ["IH"],
  },
  IE: {
    vowel: true,
    example: "pIE",
    lines: ["tor"],
    arpa: ["AY"],
  },
  IR: {
    vowel: true,
    example: "bIRd",
    lines: ["tor", "s", "bol", "bor"],
    arpa: ["ER"],
  },
  OH: {
    vowel: true,
    example: "tO(H)e",
    lines: ["tol", "tor", "s", "bol", "bor"],
    arpa: ["OW"],
  },
  OI: {
    vowel: true,
    example: "avOId",
    lines: ["bol"],
    arpa: ["OY"],
  },
  OO: {
    vowel: true,
    example: "tOO",
    lines: ["tol", "tor", "s", "bol"],
    arpa: ["UW", "UX"],
  },
  OU: {
    vowel: true,
    example: "wOUld",
    lines: ["s", "bol"],
    arpa: ["UH", "EL"],
  },
  OW: {
    vowel: true,
    example: "hOW",
    lines: ["bor"],
    arpa: ["AW"],
  },
  ORE: {
    vowel: true,
    example: "lORE",
    lines: ["tol", "tor", "s", "bor"],
    arpa: ["AO"],
  },

  B: { vowel: false, example: "Bird", lines: ["tim", "bir"], arpa: ["B"] },
  CH: { vowel: false, example: "CHat", lines: ["til", "bim"], arpa: ["CH"] },
  D: {
    vowel: false,
    example: "Dog",
    lines: ["tim", "bil", "bir"],
    arpa: ["D", "DX"],
  },
  F: {
    vowel: false,
    example: "Fox",
    lines: ["tir", "bil", "bim"],
    arpa: ["F"],
  },
  G: {
    vowel: false,
    example: "Gun",
    lines: ["tir", "bim", "bir"],
    arpa: ["G"],
  },
  H: {
    vowel: false,
    example: "Hop",
    lines: ["tim", "bim", "bir"],
    arpa: ["H", "HH"],
  },
  J: { vowel: false, example: "Jam", lines: ["tim", "bil"], arpa: ["JH"] },
  K: {
    vowel: false,
    example: "Kart",
    lines: ["tim", "tir", "bir"],
    arpa: ["K"],
  },
  L: { vowel: false, example: "Live", lines: ["tim", "bim"], arpa: ["L"] },
  M: { vowel: false, example: "Man", lines: ["bil", "bir"], arpa: ["EM", "M"] },
  N: {
    vowel: false,
    example: "Net",
    lines: ["til", "bil", "bir"],
    arpa: ["EN", "N", "NX"],
  },
  NG: {
    vowel: false,
    example: "riN(G)k",
    lines: ["til", "tim", "tir", "bil", "bim", "bir"],
    arpa: ["NG"],
  },
  P: { vowel: false, example: "Pet", lines: ["tir", "bim"], arpa: ["P"] },
  R: {
    vowel: false,
    example: "Run",
    lines: ["tim", "tir", "bim"],
    arpa: ["R"],
  },
  S: {
    vowel: false,
    example: "Sit",
    lines: ["tim", "tir", "bil", "bim"],
    arpa: ["S"],
  },
  SH: {
    vowel: false,
    example: "SHut",
    lines: ["til", "tir", "bil", "bim", "bir"],
    arpa: ["SH"],
  },
  T: {
    vowel: false,
    example: "Text",
    lines: ["til", "tir", "bim"],
    arpa: ["T"],
  },
  TH: {
    vowel: false,
    example: "THick",
    lines: ["til", "tim", "tir", "bim"],
    arpa: ["TH"],
  },
  DTH: {
    vowel: false,
    example: "(D)THis",
    lines: ["tim", "bil", "bim", "bir"],
    arpa: ["DH"],
  },
  V: {
    vowel: false,
    example: "Vine",
    lines: ["til", "tim", "bir"],
    arpa: ["V"],
  },
  W: {
    vowel: false,
    example: "Word",
    lines: ["til", "tir"],
    arpa: ["W", "WH"],
  },
  Y: {
    vowel: false,
    example: "You",
    lines: ["til", "tim", "bim"],
    arpa: ["Y"],
  },
  Z: {
    vowel: false,
    example: "Zap",
    lines: ["til", "tim", "bim", "bir"],
    arpa: ["Z"],
  },
  ZH: {
    vowel: false,
    example: "aZ(H)ure",
    lines: ["til", "tim", "tir", "bil", "bir"],
    arpa: ["ZH"],
  },
};
